# Generated by Django 5.0.1 on 2024-06-06 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_recommended_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended_posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommended_posts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
