# Generated by Django 5.0.1 on 2024-06-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='short_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
